### ISSUE TITLE
question: Why is needed that templates renaming? And second...

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate#21]
Talking about [docs/recipe/renaming-templates.md (and renaming-files.md)](https://github.com/generate/generate/blob/master/docs/recipe/renaming-templates.md) (the _dotfile, and $package.json thingy)? Can't they be just as is and generate to just copy them - renaming only if needed (through api/front-matter).

And second. Is it normal to want `index.js/generator.js` when overriding templates using `~/generate/generator-name/templates`? I think it can be a lil bit more comfortable to just be able to have the `... templates` dir and execute it as normal generator but use these templates. All that will means that `index.js/generator.js` won't be required to override templates.

**Comment by jonschlinkert** [comment]
> All that will means that index.js/generator.js won't be required to override templates.

it will use a template in the root `~/templates` if the file isn't defined in `~/templates/generate-*/templates` https://github.com/generate/generate/issues/17#issue-164647022. That's not implemented yet (would be good to keep that discussion over on that issue)

> Can't they be just as is and generate to just copy them - renaming only if needed (through api/front-matter).

No, because npm and many libraries that recurse up or down in projects will think that `templates/package.json` is a real file, or that `.gitignore` is real, etc, and some libs will use that for cwd, or look for runtime config properties inside package.json, etc. (like eslint-type libs, standard etc). we don't want there to be any potential for that, or to have to exclude them.  Aside from that, how would you recommend we do the "custom renaming" when lots of generators from different authors are used to compose a single generator? I doubt you'd want to mess with it. it's better to have conventions.

**Comment by tunnckoCore** [comment]
Hm. Yea, make sense, seems like I just didn't think it enough.
