### ISSUE TITLE
dependency tree

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#24]
to help users with debugging, let's create a visual dependency tree with "major" dependencies, with comments about what each one does. Not sure how to approach this yet, but i think it would help

**Comment by tunnckoCore** [comment]
Don't think so.. For that is the stacktraces? It is something usual issues to accept and use these stacktraces.

Or okey, think it. if we create it that way, it won't help to some newcomers or whoever, they must know the logic and cycles behind, core api and etc. These one-lines comments in form of dependency tree, won't help. It is easier for them to just paste the stacktraces which in turn are more useful for us, instead of force them to think so much.

Hm, or maybe to show by default your idea as dependency tree, and with `--verbose` to show only stacktraces.

**Comment by jonschlinkert** [comment]
Maybe you misunderstand (or I do). I want to add something that looks like this to the docs:

```js
generate
├─┬ assemble-core
│ ├── assemble-fs
│ ├── assemble-render-file
│ ├── assemble-streams
│ ├── base-task
│ └─┬ templates
│   ├── base
│   ├── base-data
│   ├── base-engines
│   ├── base-helpers
│   ├── base-option
│   ├── base-plugins
│   └── base-routes
├── assemble-loader
├── base-fs-conflicts
├── base-fs-rename
├── base-generators
├── base-npm
├── base-npm-prompt
├── base-pipeline
├── base-questions
├── base-runner
├── base-runtimes
├── base-store
├── generate-collections
└─┬ generate-defaults
  └── base-pkg
```

**Comment by jonschlinkert** [comment]
btw, it's not about stack traces, it's also about finding the documentation you need or even where to start

**Comment by tunnckoCore** [comment]
Oh yea yea. Don't know why I was thinking for output/commands/options, lol :D 
So yea, it would be in some help. :)

**Comment by jonschlinkert** [comment]
lol np.  fwiw I already started working on something to do the tree part if you want to [play around with it](https://github.com/generate/generate/blob/master/lib/tree.js). It's not wired up anywhere, so you'd need to do `node lib/tree` from the root of generate.

**Comment by jonschlinkert** [comment]
closing since this was addressed
