### ISSUE TITLE
change generator signature to match plugin signature?

### ISSUE THREAD

**Issue by jonschlinkert** [generate/generate#5]
with minor changes, I think we can make generators and plugins interchangeable. In effect, this means that generators are nothing more than plugins that are registered by name (and can be invoked by name).

We would probably want to updated `base-plugins` to pass the `base` instance as the second argument to plugins. example:

```js
function plugin(app, base) {
  // do plugin stuff
}
this.run(plugin(app, base));
```

thoughts? cc @doowb

**Comment by doowb** [comment]
:+1: 

- Would we use `.use` inside something like `.register` or `.generator`?
  I think this makes sense because then we can register the name, lazyily invoke it, and look it up later.

- Do we even need to differentiate between it being a plugin and a generator?
  I don't think we do necessarily. Generators will be registered as above, but then when calling `.use` on them, they can return a function that can be used as a plugin on additional generators.

You probably have a better idea of where that code will go, but I think it makes sense.

**Comment by jonschlinkert** [comment]
yeah, very similar to what I had in mind. I don't see a difference either

I was thinking we could create customized versions of `.use` and `.run`. but instead of `.run` we could use `.invoke` or something. but we might not need to.

**Comment by tunnckoCore** [comment]
Same here :+1: 
Use the `.use` inside `.register`, have `.invoke` and remove `.extendWith`.

**Comment by jonschlinkert** [comment]
@doowb and I spent hours going over this today. to this point, most of the base-generators/env/resolving logic was just created to help us figure out what we wanted to accomplish. I think we know now, so all of those things will be refactored fairly quickly.

thanks for the feedback
